-- 9.6.1
SELECT P.COD_PESSOA, P.NOME_PESSOA NOME, M.NOME_MODALIDADE MODALIDADE 
	FROM PESSOA P INNER JOIN MODALIDADE M 
	ON P.COD_MODALIDADE = M.COD_MODALIDADE
	ORDER BY NOME ASC;

-- 9.6.2
SELECT P.NOME_PESSOA NOME, C.LINHA LINHA, PP.SALDO_ANTERIOR SALDO, PP.DATA DATA_PGT
	FROM PESSOA P INNER JOIN PGT_PASSAGEM PP
	ON P.COD_PESSOA = PP.COD_PESSOA
	INNER JOIN LOCAL_BUS LB
	ON PP.COD_LOCALIZACAO = LB.COD_LOCALIZACAO
	INNER JOIN COLETIVO C
	ON C.COD_COLETIVO = LB.COD_COLETIVO;